"""empty message

Revision ID: 3cd520007dfe
Revises: 55174c6606c5
Create Date: 2020-05-06 21:22:13.584495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd520007dfe'
down_revision = '55174c6606c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'failure',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'success',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'success',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'failure',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
