"""empty message

Revision ID: 55174c6606c5
Revises: 499dabcee0d9
Create Date: 2020-05-06 20:59:38.165646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55174c6606c5'
down_revision = '499dabcee0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('failure', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'failure')
    # ### end Alembic commands ###
