"""empty message

Revision ID: 8d84cf8648a0
Revises: f9084aa64b1a
Create Date: 2020-05-04 23:35:50.140587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d84cf8648a0'
down_revision = 'f9084aa64b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('textcolor', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'textcolor')
    # ### end Alembic commands ###
