"""empty message

Revision ID: a035c201fcab
Revises: 8d84cf8648a0
Create Date: 2020-05-05 19:37:01.658978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a035c201fcab'
down_revision = '8d84cf8648a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drop', sa.Column('drop_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drop', 'drop_date')
    # ### end Alembic commands ###
