"""empty message

Revision ID: ac95470c987f
Revises: fe733fb4750a
Create Date: 2020-05-04 21:37:02.175654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac95470c987f'
down_revision = 'fe733fb4750a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('closed', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot', 'closed')
    # ### end Alembic commands ###
