"""empty message

Revision ID: b5e176df7028
Revises: 915d3352d0fc
Create Date: 2020-05-04 22:43:14.024582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e176df7028'
down_revision = '915d3352d0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'color',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'color',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
