"""empty message

Revision ID: bb250fd473bc
Revises: a035c201fcab
Create Date: 2020-05-06 17:04:45.317900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb250fd473bc'
down_revision = 'a035c201fcab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmedSlots',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('pendingSlots',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.alter_column('drop', 'drop_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drop', 'drop_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('pendingSlots')
    op.drop_table('confirmedSlots')
    # ### end Alembic commands ###
