"""empty message

Revision ID: caddff20f01d
Revises: ff1dc9e841da
Create Date: 2020-05-04 19:33:40.530457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caddff20f01d'
down_revision = 'ff1dc9e841da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drop', sa.Column('slug', sa.String(length=128), nullable=True))
    op.drop_column('drop', 'drop_slug')
    op.add_column('slot', sa.Column('slug', sa.String(length=128), nullable=True))
    op.drop_column('slot', 'slot_slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('slot_slug', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('slot', 'slug')
    op.add_column('drop', sa.Column('drop_slug', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('drop', 'slug')
    # ### end Alembic commands ###
