"""empty message

Revision ID: d26eeda531b7
Revises: bb3014a68ec9
Create Date: 2020-05-04 19:27:00.133906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26eeda531b7'
down_revision = 'bb3014a68ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drop', sa.Column('slug', sa.String(length=128), nullable=True))
    op.add_column('slot', sa.Column('slug', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot', 'slug')
    op.drop_column('drop', 'slug')
    # ### end Alembic commands ###
