"""empty message

Revision ID: f9084aa64b1a
Revises: b5e176df7028
Create Date: 2020-05-04 23:32:39.035916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9084aa64b1a'
down_revision = 'b5e176df7028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('textcolor', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'textcolor')
    # ### end Alembic commands ###
